<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address type HomeOffice_fld_cpassword</name>
   <tag></tag>
   <elementGuidId>1fa945f8-2956-4e4c-9358-b6fe85b95b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fld_cpassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fld_cpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0928505f-e0b7-425b-819b-1e271700310f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>ba2cc47a-2784-4689-be29-55903d902fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fld_cpassword</value>
      <webElementGuid>402a9443-6dc4-4d69-b5c6-e38c39cf05d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>40cdf770-9710-46b2-a8bb-9317ec53e6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm password</value>
      <webElementGuid>203b53c2-4c84-4409-9314-4f28318f3dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content1&quot;)/form[1]/input[@class=&quot;field&quot;]</value>
      <webElementGuid>9b9cd503-79fa-422e-a940-6aae55718c01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fld_cpassword']</value>
      <webElementGuid>44f51a90-ea0b-417b-be70-e9895044d058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/input[5]</value>
      <webElementGuid>2c7bff6f-ef2a-4311-8545-0dad756865fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>20d1bd1d-8632-459c-acec-b2b3ab265aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'fld_cpassword' and @type = 'password' and @placeholder = 'Confirm password']</value>
      <webElementGuid>ba8abe6e-824b-4462-b621-f78f1b652e10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
