<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Button</name>
   <tag></tag>
   <elementGuidId>a939fe88-3177-423a-a8cc-eb9c828e74d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gh-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41da0a1f-942f-4c76-ad12-42baf3dfb286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f66da233-1ba5-4c16-ae09-5d8911b9cf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-prim gh-spr</value>
      <webElementGuid>e0a9be44-9454-44a3-a2c6-0236c2df6728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-btn</value>
      <webElementGuid>b098eeb8-cf7c-488f-9d55-546459328914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>49d2a4d1-cc68-4003-bb5b-d23fd79308df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-btn&quot;)</value>
      <webElementGuid>e0f3b393-cc33-49da-8128-0f32df28c7eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gh-btn']</value>
      <webElementGuid>ce0c16cd-3188-4bfe-8c86-d2e073413ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gh-f']/table/tbody/tr/td[3]/input</value>
      <webElementGuid>432ea7e8-5cec-4563-949c-f8cd45671814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>2416892e-b138-40ba-9a65-c814916680ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'gh-btn']</value>
      <webElementGuid>b062d5eb-3cc8-45bd-8d16-861b16633575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
