<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Category</name>
   <tag></tag>
   <elementGuidId>6cf349fa-21d0-49e6-bb00-efb6d702fde7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-cat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gh-cat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9295484c-baca-404c-833c-a1ae23bf4667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select a category for search</value>
      <webElementGuid>e7498bde-c3af-40bb-b998-14209da2e928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-sb </value>
      <webElementGuid>b604ac37-106a-4c40-b80b-b5c906b50cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e9562aad-84e7-4c27-ad27-c1eff85cd363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-cat</value>
      <webElementGuid>ed1a5f7d-04ee-4604-b2ab-708c258d7e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_sacat</value>
      <webElementGuid>cf385f2c-9498-4503-8b26-db4d0d4a9573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All CategoriesAntiquesArtBabyBooksBusiness &amp; IndustrialCameras &amp; PhotoCell Phones &amp; AccessoriesClothing, Shoes &amp; AccessoriesCoins &amp; Paper MoneyCollectiblesComputers/Tablets &amp; NetworkingConsumer ElectronicsCraftsDolls &amp; BearsDVDs &amp; MovieseBay MotorsEntertainment MemorabiliaGift Cards &amp; CouponsHealth &amp; BeautyHome &amp; GardenJewelry &amp; WatchesMusicMusical Instruments &amp; GearPet SuppliesPottery &amp; GlassReal EstateSpecialty ServicesSporting GoodsSports Mem, Cards &amp; Fan ShopStampsTickets &amp; ExperiencesToys &amp; HobbiesTravelVideo Games &amp; ConsolesEverything Else</value>
      <webElementGuid>12d94c20-be82-46e9-b1df-99b056a5d552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-cat&quot;)</value>
      <webElementGuid>b953954e-f411-4103-9fb6-820ac6ea4ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gh-cat']</value>
      <webElementGuid>cc3975f0-02e3-4675-a440-67e4b63e997a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gh-cat-box']/select</value>
      <webElementGuid>6c469912-b1a1-4e03-bb57-5706c70016af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your search keyword'])[1]/following::select[1]</value>
      <webElementGuid>0bb5b3b2-f1fb-4fca-92cf-f65e70cd4c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all categories'])[1]/following::select[1]</value>
      <webElementGuid>3bfcee3d-08a8-4e59-94d5-e1581dc65b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/preceding::select[1]</value>
      <webElementGuid>69780641-5a45-45ce-b935-ac2fcc0fbca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>206c6b53-e90f-4ba2-b97f-7391bdd242cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gh-cat' and @name = '_sacat' and (text() = 'All CategoriesAntiquesArtBabyBooksBusiness &amp; IndustrialCameras &amp; PhotoCell Phones &amp; AccessoriesClothing, Shoes &amp; AccessoriesCoins &amp; Paper MoneyCollectiblesComputers/Tablets &amp; NetworkingConsumer ElectronicsCraftsDolls &amp; BearsDVDs &amp; MovieseBay MotorsEntertainment MemorabiliaGift Cards &amp; CouponsHealth &amp; BeautyHome &amp; GardenJewelry &amp; WatchesMusicMusical Instruments &amp; GearPet SuppliesPottery &amp; GlassReal EstateSpecialty ServicesSporting GoodsSports Mem, Cards &amp; Fan ShopStampsTickets &amp; ExperiencesToys &amp; HobbiesTravelVideo Games &amp; ConsolesEverything Else' or . = 'All CategoriesAntiquesArtBabyBooksBusiness &amp; IndustrialCameras &amp; PhotoCell Phones &amp; AccessoriesClothing, Shoes &amp; AccessoriesCoins &amp; Paper MoneyCollectiblesComputers/Tablets &amp; NetworkingConsumer ElectronicsCraftsDolls &amp; BearsDVDs &amp; MovieseBay MotorsEntertainment MemorabiliaGift Cards &amp; CouponsHealth &amp; BeautyHome &amp; GardenJewelry &amp; WatchesMusicMusical Instruments &amp; GearPet SuppliesPottery &amp; GlassReal EstateSpecialty ServicesSporting GoodsSports Mem, Cards &amp; Fan ShopStampsTickets &amp; ExperiencesToys &amp; HobbiesTravelVideo Games &amp; ConsolesEverything Else')]</value>
      <webElementGuid>39fa7f59-1f72-4fb8-bddf-93173dc4d191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
